apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "vaultplane.fullname" . }}
  labels:
    {{- include "vaultplane.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "vaultplane.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        # Roll the pods whenever the ConfigMap (and therefore the gateway
        # config) changes, even if other Deployment fields stayed the
        # same.
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "vaultplane.selectorLabels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      serviceAccountName: {{ include "vaultplane.serviceAccountName" . }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: gateway
          image: {{ include "vaultplane.image" . | quote }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - "--config"
            - "/etc/vaultplane/vaultplane.yaml"
          ports:
            - name: proxy
              containerPort: 8080
              protocol: TCP
            - name: admin
              containerPort: 9091
              protocol: TCP
          envFrom:
            - secretRef:
                name: {{ include "vaultplane.secretName" . }}
          {{- with .Values.env }}
          env:
            {{- range $key, $val := . }}
            - name: {{ $key }}
              value: {{ $val | quote }}
            {{- end }}
          {{- end }}
          volumeMounts:
            - name: config
              mountPath: /etc/vaultplane
              readOnly: true
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          securityContext:
            {{- toYaml .Values.containerSecurityContext | nindent 12 }}
      volumes:
        - name: config
          configMap:
            name: {{ include "vaultplane.fullname" . }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
