{{- if .Values.serviceMonitor.enabled -}}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "vaultplane.fullname" . }}
  labels:
    {{- include "vaultplane.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "vaultplane.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: admin
      path: /admin/metrics
      interval: {{ .Values.serviceMonitor.interval }}
      scrapeTimeout: {{ .Values.serviceMonitor.scrapeTimeout }}
      {{- with .Values.serviceMonitor.bearerTokenSecret.name }}
      authorization:
        type: Bearer
        credentials:
          name: {{ . }}
          key: {{ $.Values.serviceMonitor.bearerTokenSecret.key }}
      {{- end }}
{{- end -}}
